name: EconomyTax
main: onebone\economytax\EconomyTax
author: onebone
version: "2.0.3-dev1"
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6]
depend: [EconomyAPI]
permissions:
 economytax.tax.avoid:
  description: The permission that allows player to avoid paying tax
  deafault: op
