name: EconomyUsury
version: "1.0.1"
author: onebone
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
main: onebone\economyusury\EconomyUsury
depend: [EconomyAPI]

permissions:
 economyusury.*:
  description: Gives player all access permissions to EconomyUsury
  children:
   economyusury.command.*:
    description: Gives player all access permissions of commands
    children:
     economyusury.command.usury:
      description: Gives player permission to execute usury command
      default: true
      children:
       economyusury.command.usury.host:
        description: Gives player permission to execute usury host command
        default: true
        children:
         economyusury.command.usury.host.open:
          description: Gives player permission to open usury host by command
          default: true
         economyusury.command.usury.host.close:
          description: Gives player permission to close usury host by command
